// POST /2fa/setup
// POST /2fa/verify
// POST /2fa/complete-login

import type { FastifyPluginAsync } from "fastify";
import type { ZodTypeProvider } from "fastify-type-provider-zod";
import { authGuard } from "../../../middleware/authGuard.js";
import { twoFactorController } from "../controller/two-factor.controller.js";
import {
  completeTwoFactorLoginSchema,
  twoFactorCompleteLoginResponseSchema,
  twoFactorSetupResponseSchema,
  twoFactorVerifyResponseSchema,
  verifyTwoFactorSchema,
} from "../schemas/two-factor.schema.js";
import { errorResponseSchema } from "../../../common/common.schema.js";

const twoFactorRoutes: FastifyPluginAsync = async (fastify) => {
  const app = fastify.withTypeProvider<ZodTypeProvider>();

  app.post(
    "/setup",
    {
      schema: {
        tags: ["Two-Factor Authentication"],
        summary: "Initiate 2FA setup",
        description:
          "Generates a new TOTP secret key and QR code URI for the authenticated user to register with an authenticator app.",
        security: [{ bearerAuth: [] }, { cookieAuth: [] }],
        response: {
          200: twoFactorSetupResponseSchema,
          401: errorResponseSchema,
          409: errorResponseSchema,
        },
      },
      preHandler: authGuard,
    },
    twoFactorController.setup
  );

  app.post(
    "/verify",
    {
      schema: {
        tags: ["Two-Factor Authentication"],
        summary: "Verify and activate 2FA",
        description:
          "Verifies a 6-digit TOTP code generated by the user's authenticator app and permanently enables 2FA on the account.",
        security: [{ bearerAuth: [] }, { cookieAuth: [] }],
        body: verifyTwoFactorSchema,
        response: {
          200: twoFactorVerifyResponseSchema,
          400: errorResponseSchema,
          401: errorResponseSchema,
          409: errorResponseSchema,
        },
      },
      preHandler: authGuard,
    },
    twoFactorController.verify
  );

  // Completes 2FA login: accepts challengeToken (from POST /api/auth/login) + TOTP code
  // No authGuard — the user does not have a real session yet
  app.post(
    "/complete-login",
    {
      schema: {
        tags: ["Two-Factor Authentication"],
        summary: "Complete 2FA login challenge",
        description:
          "Exchanges a temporary 2FA challenge token and 6-digit TOTP code for authenticated user session and HttpOnly cookies.",
        body: completeTwoFactorLoginSchema,
        response: {
          200: twoFactorCompleteLoginResponseSchema,
          400: errorResponseSchema,
          401: errorResponseSchema,
        },
      },
    },
    twoFactorController.completeLogin
  );
};

export default twoFactorRoutes;
